name: Qodo Merge

on:
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  pr_agent_job:
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request) }}
    runs-on: ubuntu-latest
    name: Run Qodo Merge
    steps:
      - name: Qodo Merge action step
        id: pragent
        uses: Codium-ai/pr-agent@0bd56c0508504c718cc03d504cd4ceb6725ba3c7
        env:
          CONFIG.AI_PROVIDER: google
          GEMINI_API_KEY: ${{ secrets.GOOGLE_AI_STUDIO_KEY }}
          CONFIG.MODEL: gemini/gemini-2.5-flash
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.RESPONSE_LANGUAGE: ru
